name: Python CI/CD Demo

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

  deploy:
    needs: test   # only run if tests succeed
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Cloud
        run: echo "Deploying application..." 
        # replace with actual cloud deployment command
        # Example for Heroku:
        #   git push heroku main
        # Example for AWS (Elastic Beanstalk / Lambda):
        #   aws deploy create-deployment ...
